export const OffersType = {
  CHANGE_CITY: `CHANGE_CITY`,
  GET_OFFERS: `GET_OFFERS`,
  GET_OFFER: `GET_OFFER`,
  FILTER_OFFER: `FILTER_OFFER`,
  GET_FAVORITE: `GET_FAVORITE`
};
export const UserType = {
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  RESULT: ``,
  AUTH: `AUTH`,
  NO_AUTH: `NO_AUTH`,
};
export const ReviewType = {
  ADD_REVIEWS: `ADD_REVIEWS`,
  GET_REVIEWS: `GET_REVIEWS`
};
