export const OffersType = {
  CHANGE_CITY: `CHANGE_CITY`,
  GET_OFFERS: `GET_OFFERS`,
  GET_OFFER: `GET_OFFER`,
  REMOVE_FAVORITE: `REMOVE_FAVORITE`,
  FILTER_OFFER: `FILTER_OFFER`,
  REDIRECT_TO_ROUTE: `REDIRECT_TO_ROUTE`,
  GET_REVIEWS: `GET_REVIEWS`,
  ADD_REVIEWS: `ADD_REVIEWS`,
  SET_FAVORITE: `SET_FAVORITE`,
  GET_FAVORITE: `GET_FAVORITE`,
  ERROR_LOAD: `ERROR_LOAD`,
  ERROR_OFFER: `ERROR_OFFER`,
  ERROR_GET_FAVORITE: `ERROR_GET_FAVORITE`,
  ERROR_SET_FAVORITE: `ERROR_SET_FAVORITE`,
};

export const UserType = {
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  RESULT: ``,
  AUTH: `AUTH`,
  NO_AUTH: `NO_AUTH`,
  REQUIRED_ERROR: `REQUIRED_ERROR`,
};

export const ReviewType = {
  ADD_REVIEWS: `ADD_REVIEWS`,
  GET_REVIEWS: `GET_REVIEWS`,
  ERROR_LOAD: `ERROR_LOAD`,
  ERROR_ADD: `ERROR_ADD`
};

export const AppRoute = {
  RESULT: `/`,
  LOGIN: `/login`
};

const BASE_URL = `https://5.react.pages.academy/six-cities/`;

export const APIRoute = {
  GET_OFFER: BASE_URL + `hotels`,
  GET_REVIEWS: BASE_URL + `comments`,
  LOGIN: BASE_URL + `login`,
  REDIRECT_TO_ROUTE: `REDIRECT_TO_ROUTE`,
  FAVORITE: BASE_URL + `favorite`,
};

export const ActionFilter = {
  FILTER_POPULAR: `Popular`,
  FILTER_TOP_RATED_FIRST: `Top rated first`,
  FILTER_PRICE_LOW_TO_HIGH: `Price: low to high`,
  FILTER_PRICE_HIGH_TO_LOW: `Price: high to low`,
};
